version: '3.8'

services:
  nginx:
    volumes:
      - ./nginx/conf.d/production.conf:/etc/nginx/conf.d/default.conf:ro

  server:
    command: npm start --workspace=@maycast/server
    environment:
      - LOG_LEVEL=info

  web-client:
    command: npm run preview --workspace=web-client
